IGetThatReference/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.urlpatterns import format_suffix_patterns
import references.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', references.views.home, name='home'),
    path('references/', include('references.urls')),
    path('api/', references.views.ReferenceList.as_view()),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

references/urls.py
from django.urls import path, re_path
from . import views

app_name = 'references'

urlpatterns = [
    re_path('^tag/(?P<tag_name>[\w\W\s]+)/', views.tag, name='tag'),
    re_path('^search/', views.search, name='search'),
    re_path('^unique/(?P<id>[0-9]+)/', views.unique, name='unique'),
]

references/models.py
from django.db import models
import json

# Create your models here.
class Reference(models.Model):

    quote = models.TextField()
    author = models.CharField(max_length=100)
    source = models.CharField(max_length=100)
    tags = models.TextField()
    pub_date = models.DateTimeField()

references/views.py
from django.shortcuts import render, redirect, get_object_or_404
from rest_framework.views import APIView

from rest_framework.response import Response
from rest_framework import status

# from django.views import View
# from django.views.generic import TemplateView, ListView, DetailView
# from django.http import HttpResponse

from .models import Reference
from .serializer import ReferenceSerializer


# Create your views here.
def home(request):

    references = Reference.objects.order_by('-pub_date')
    tags = [list(map(str.strip, reference.tags.split(','))) for reference in references]

    context = {'info': zip(references, tags)}

    return render(request, 'references/home.html', context)



def tag(request, tag_name):

    references = [reference for reference in Reference.objects.order_by('-pub_date') if tag_name in reference.tags]
    tags = [list(map(str.strip, reference.tags.split(','))) for reference in references]

    context = {
                'type': 'tag',
                'info': zip(references, tags),
                'input': tag_name
            }

    return render(request, 'references/tagsearch.html', context)



def search(request):

    def search(search_params):
        params = list(map(str.lower, search_params.split()))

        references = []
        for reference in Reference.objects.order_by('-pub_date'):

            quote = reference.quote
            author = reference.author
            source = reference.source
            tags = reference.tags
            mish = (quote + author + source + tags).lower()

            for param in params:
                if (param in mish) and (reference not in references):
                    references.append(reference)

        return references

    if request.method == 'GET':
        search_param = request.GET['params']
        references = search(search_param)
        tags = [list(map(str.strip, reference.tags.split(','))) for reference in references]

        context = {
            'type': 'search',
            'info': zip(references, tags),
            'input': search_param
        }

        return render(request, 'references/tagsearch.html', context)

def unique(request, id):

    references = [Reference.objects.get(pk=id)]
    tags = [list(map(str.strip, reference.tags.split(','))) for reference in references]

    context = {'info': zip(references, tags)}

    return render(request, 'references/home.html', context)


# Lists all stocks and get new one
class ReferenceList(APIView):
    def get(self, request):
        references = Reference.objects.all()
        serializer = ReferenceSerializer(references, many=True)

        return Response(serializer.data)

    def post(self, request):
        serializer =  ReferenceSerializer(data=request.data)
        print(request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

references/templates/references/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    IGTR!
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'references/css/reference.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'references/js/options.js' %}"></script>
{% endblock %}

{% block content %}


        {% for reference, tags in info %}

            <div class="row">

            {% if forloop.counter0 == 0 %}
                <div id="quote-{{ reference.id }}" class="col-md-8 offset-md-2 latest">
            {% else %}
                <div id="quote-{{ reference.id }}"  class="col-md-8 offset-md-2">
            {% endif %}

                    <div class="quote">

                        {{ reference.quote }}

                        <br>

                        <div class="citation">
                            -
                            <span class="author">{{ reference.author }}</span>,
                            <span class="source">{{ reference.source }}</span>
                        </div>

                    </div>

                    <br>
                    <hr>

                    <div class="menu">

                        <div class="tags">

                            {% for tag in tags %}
                                <a id="tag-{{ reference.id }}-{{ tag }}" class="tag" href="{% url 'references:tag' tag%}" target="_blank">#{{ tag }}</a>
                            {% endfor %}
                        </div>

                        <div class="options">
                            <a id="unique-{{ reference.id }}" href="{% url 'references:unique' reference.id%}" class="option unique" target="_blank"><i class="fa fa-info" aria-hidden="true"></i></a>
                            <a id="copy-{{ reference.id }}" href="#!" class="option copy"><i class="fa fa-clipboard" aria-hidden="true"></i></a>
                        </div>

                    </div>

            </div>

            </div>
            <br>
            <br>
        {% endfor %}

{% endblock %}

references/templates/references/tagsearch.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    IGTR!
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'references/css/reference.css' %}">
{% endblock %}

{% block scripts %}
    <script src="{% static 'references/js/options.js' %}"></script>
{% endblock %}

{% block content %}

            <br>
            <br>
            <br>

            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <h4 id="desc">
                        {% if type == 'tag' %}
                        Posts with the tag "{{ input }}".
                        {% else %}
                        Search results for "{{ input }}".
                        {% endif %}
                    </h4>
                </div>
            </div>

            <br>
            <br>

        {% for reference, tags in info %}

            <div class="row">

                <div id="quote-{{ reference.id }}"  class="col-md-8 offset-md-2">

                    <div class="quote">

                        {{ reference.quote }}

                        <br>

                        <div class="citation">
                            -
                            <span class="author">{{ reference.author }}</span>,
                            <span class="source">{{ reference.source }}</span>
                        </div>

                    </div>

                    <br>
                    <hr>

                    <div class="menu">

                        <div class="tags">

                            {% for tag in tags %}
                                <a id="tag-{{ reference.id }}-{{ tag }}" class="tag" href="{% url 'references:tag' tag%}" target="_blank">#{{ tag }}</a>
                            {% endfor %}
                        </div>

                        <div class="options">
                            <a id="unique-{{ reference.id }}" href="{% url 'references:unique' reference.id%}" class="option unique" target="_blank"><i class="fa fa-info" aria-hidden="true"></i></a>
                            <a id="copy-{{ reference.id }}" href="#!" class="option copy"><i class="fa fa-clipboard" aria-hidden="true"></i></a>
                        </div>

                    </div>

            </div>

            </div>
            <br>
            <br>
        {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>

    {% load static %}

    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'references/css/default.css' %}">
    <link rel="stylesheet" href="{% static 'references/css/navbar.css' %}">
    {% block css %}{% endblock %}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    {% block scripts %}{% endblock %}

</head>
<body>


    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a href="{% url 'home' %}" class="navbar-brand">I Get That Reference!</a>
            <button class="navbar-toggler float-right" type="button" data-toggle="collapse" data-target="#my_navbar">
                <span class="navbar-toggler-icon">☰</span>
            </button>
            <div class="navbar-collapse collapse" id="my_navbar">
                <ul class="navbar-nav ml-auto">
                    <li>
                        <div id="search-box">
                            <form method="get" action="{% url 'references:search' %}">
                                <input id="search-text" name="params" type="text">
                                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

</body>
</html>